In [172]:
import pandas as pd

In [173]:
# read in team 1 data
data1 = pd.read_csv("Final_Score/Golden State Warriors.csv", index_col="Unnamed: 0")

In [174]:
# read in team 2 data
data2 = pd.read_csv("Final_Score/Los Angeles Lakers.csv", index_col="Unnamed: 0")

In [176]:
#create index with both datasets
new_index = data1.index.append(data2.index)

In [177]:
# append first teams stats
test = data1["0"].tolist()

In [178]:
# append second teams stats
for X in data2["0"].tolist():
    test.append(X)

In [179]:
# create datframe
nba_stats = pd.DataFrame(test)

In [180]:
# make column from index with names
nba_stats["Name"] = new_index

In [181]:
# rename column scores 
nba_stats.rename(columns={0: "scores"}, inplace=True)

In [182]:
nba_stats

       scores                    Name
0   20.050000          Andrew Wiggins
1    6.788462            Anthony Lamb
2    5.375000        Donte DiVincenzo
3   18.333333          Draymond Green
4    8.828571          JaMychal Green
5   17.575000           James Wiseman
6    7.517857         Jerome Robinson
7   32.725000        Jonathan Kuminga
8   34.425000            Jordan Poole
9   21.825000            Kevon Looney
10  26.250000           Klay Thompson
11   1.250000         Lester Quinones
12  19.000000             Mac McClung
13   6.292857             Moses Moody
14   2.050000             Pat Spencer
15  13.900000     Patrick Baldwin Jr.
16   4.778571  Quinndary Weatherspoon
17   3.250000            Ryan Rollins
18  34.275000           Stephen Curry
19  12.500000        Trevion Williams
20   7.000000               Ty Jerome
21  38.750000           Anthony Davis
22  12.333333           Austin Reaves
23  12.700000             Cole Swider
24   7.816667            Damian Jones
25   0.750000         Dennis Schroder
26  13.500000            Dwayne Bacon
27  13.270833                Jay Huff
28  11.560811   Juan Toscano-Anderson
29  22.773256           Kendrick Nunn
30  11.500000            LeBron James
31  21.740385        Lonnie Walker IV
32  20.892442               Matt Ryan
33  15.000000            Max Christie
34   8.500000       Nate Pierre-Louis
35   9.175000        Patrick Beverley
36   4.600000       Russell Westbrook
37  11.150000       Scotty Pippen Jr.
38   6.750000      Shaquille Harrison
39  17.833333           Thomas Bryant
40  15.466667          Wenyen Gabriel

In [183]:
# obtain DKG salary file
DKG_salary = pd.read_csv("DKSalaries.csv")

In [184]:
DKG_salary

,Position,Name + ID,Name,ID,Roster Position,Salary,Game Info,TeamAbbrev,AvgPointsPerGame
0,PG,Stephen Curry (24621233),Stephen Curry,24621233,CPT,15600,LAL@GSW 10/18/2022 10:00PM ET,GSW,46.15
1,SF/PF,LeBron James (24621234),LeBron James,24621234,CPT,15000,LAL@GSW 10/18/2022 10:00PM ET,LAL,55.15
2,PF/C,Anthony Davis (24621235),Anthony Davis,24621235,CPT,14100,LAL@GSW 10/18/2022 10:00PM ET,LAL,46.86
3,PG,Russell Westbrook (24621236),Russell Westbrook,24621236,CPT,12300,LAL@GSW 10/18/2022 10:00PM ET,LAL,40.32
4,SF,Andrew Wiggins (24621237),Andrew Wiggins,24621237,CPT,11700,LAL@GSW 10/18/2022 10:00PM ET,GSW,30.66
...,...,...,...,...,...,...,...,...,...
71,PG/SG,Ryan Rollins (24621304),Ryan Rollins,24621304,UTIL,1000,LAL@GSW 10/18/2022 10:00PM ET,GSW,0.00
72,SF,Jerome Robinson (24621305),Jerome Robinson,24621305,UTIL,1000,LAL@GSW 10/18/2022 10:00PM ET,GSW,0.00
73,SG,Dwayne Bacon (24621306),Dwayne Bacon,24621306,UTIL,1000,LAL@GSW 10/18/2022 10:00PM ET,LAL,0.00
74,PG,Javante McCoy (24621307),Javante McCoy,24621307,UTIL,1000,LAL@GSW 10/18/2022 10:00PM ET,LAL,0.00
75,C,Jay Huff (24621308),Jay Huff,24621308,UTIL,1000,LAL@GSW 10/18/2022 10:00PM ET,LAL,2.50

In [185]:
# salary for players
UTIL = DKG_salary.loc[DKG_salary["Roster Position"] == "UTIL",:]

In [186]:
# salary for captains
CPT = DKG_salary.loc[DKG_salary["Roster Position"] == "CPT"]

In [187]:
#creates alt scores with avg ppg provided by draftkings
alt_scores = DKG_salary["AvgPointsPerGame"]

In [188]:
# makes new name list
new_names = nba_stats["Name"].tolist()

In [189]:
dk_names = DKG_salary['Name']

names_drop = []

for name in dk_names:
    if name not in new_names:
        print(f"Not current: {name}")
        
        


for name in new_names:
    if name not in dk_names.tolist():
        print(f"Roster: {name}")
        names_drop.append(name)

Not current: Andre Iguodala
Not current: Troy Brown Jr.
Not current: Andre Iguodala
Not current: Troy Brown Jr.
Not current: Javante McCoy
Not current: Javante McCoy
Roster: Anthony Lamb
Roster: Mac McClung
Roster: Trevion Williams
Roster: Ty Jerome
Roster: Nate Pierre-Louis
Roster: Shaquille Harrison

In [190]:
for replace in names_drop:
    nba_stats  = nba_stats.loc[nba_stats["Name"] != replace]

In [191]:
# change name to be compaitble with draftkings
new_names[27] = "Robert Williams"

nba_stats["Name"] = new_names

ValueError: Length of values (41) does not match length of index (35)

In [192]:
# iterates through UTIL to get salary
s = []
t = []
for x in nba_stats["Name"]:
    
    
    if x in dk_names.tolist():
        row = UTIL.loc[UTIL["Name"] == x]
        s.append(row["Salary"].values[0])
        t.append(row["AvgPointsPerGame"].values[0])

In [193]:
#     for row in UTIL.iterrows():
#        if x == row[1]["Name"]:
#            s.append(row[1]["Salary"])
#            t.append(row[1]["AvgPointsPerGame"])

In [194]:
#makes column with salary
nba_stats["UTIL_salary"] = s

nba_stats["Alt_Salary"] = t

In [195]:
# gets CPT salary by 1.5 X UTIL
nba_stats["CPT_Salary"] = nba_stats["UTIL_salary"] * 1.5

In [196]:
drop_columns = nba_stats.sort_values(by="scores").head(10)["Name"].tolist()

In [197]:
name_list = nba_stats.sort_values(by="scores", ascending=False).head(43)["Name"].tolist()

In [124]:
len(nba_stats)

53

In [101]:
# list of players to keep
name_list = ['Jayson Tatum',
 'Stephen Curry',
 'Jaylen Brown',
 'Al Horford',
 'Andrew Wiggins',
 'Klay Thompson',
 'Marcus Smart',
 'Draymond Green',
 'Jordan Poole',
 'Kevon Looney',
 'Derrick White', 
    'Gary Payton II',
            'Robert Williams']

In [198]:
# list of columns to drop 
drop_columns = [
 'Dennis Schroder',
 'Dwayne Bacon',
 'Jay Huff',
 'Juan Toscano-Anderson',
 'Kendrick Nunn',
'Lonnie Walker IV',
 'Matt Ryan',
 'Max Christie',
 'Patrick Beverley',
 'Russell Westbrook',
 'Scotty Pippen Jr.',
 'Thomas Bryant',
 'Wenyen Gabriel',
    'Patrick Baldwin Jr.',
    'Moses Moody',
    'Cole Swider',
 'Damian Jones',
    
]

In [199]:
name_list = []
list_name = nba_stats["Name"]

for name in list_name:
    if name not in drop_columns:
        name_list.append(name)

In [202]:
index_drop = []
for i in drop_columns:
    row = nba_stats.loc[nba_stats["Name"] == i]
    index_drop.append(row.index[0])

In [203]:
for i in name_list:
    row = nba_stats.loc[nba_stats["Name"] == i]
    total_points = row["scores"]
    total_salary = 50000 - row["CPT_Salary"]

In [204]:
from itertools import combinations
total_lists = []
temp_chosen = []

for i in name_list:
    row = nba_stats.loc[nba_stats["Name"] == i]
    score = row["scores"].tolist()[0] * 1.5
    max_salary = 50000 - row["CPT_Salary"].tolist()[0]

    comb = nba_stats.drop(index = index_drop)
    comb = comb.sort_values("scores", ascending=False).copy()
    cpt_name = row["Name"].tolist()[0]
    print(cpt_name)
    print(score)
    temp_chosen.append({cpt_name : score})

    legit = ()
    max_score = 0

    comb = comb.drop(row.index)
    for combo in combinations(comb["Name"], 5):  # 2 for pairs, 3 for triplets, etc
        total_score = 0
        total_salary = 0
        for x in combo:
            rowP = nba_stats.loc[nba_stats["Name"] == x]
            total_score = total_score + rowP["scores"].tolist()[0]
            total_salary = total_salary + rowP["UTIL_salary"].tolist()[0]
        total_score = total_score + score
        if total_salary < max_salary:
            if total_score > max_score:
                team_salary = total_salary
                print(total_score)
                max_score = total_score
                legit = combo
                print(legit)
                
    temp_chosen.append({max_score : legit})

Andrew Wiggins
30.075000000000003
192.075
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Kevon Looney')
Donte DiVincenzo
8.06249999999999
174.48749999999998
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Draymond Green
27.499999999999993
193.92499999999998
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
JaMychal Green
13.242857142857149
179.66785714285714
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
James Wiseman
26.362499999999994
192.78749999999997
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Jerome Robinson
11.276785714285715
177.7017857142857
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Jonathan Kuminga
49.08749999999999
204.61249999999995
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Klay Thompson', 'Kevon Looney')
Jordan Poole
51.637499999999996
205.46249999999998
('Anthony Davis', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson', 'Kevon Looney')
Kevon Looney
32.737500000000004
199.1625
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Klay Thompson
39.375
201.375
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Kevon Looney')
Lester Quinones
1.8750000000000053
168.29999999999998
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Pat Spencer
3.0750000000000064
169.5
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Quinndary Weatherspoon
7.167857142857143
173.59285714285713
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Ryan Rollins
4.875
171.29999999999998
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
Stephen Curry
51.412499999999994
205.38749999999996
('Anthony Davis', 'Jordan Poole', 'Jonathan Kuminga', 'Klay Thompson', 'Kevon Looney')
Anthony Davis
58.125
207.625
('Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson', 'Kevon Looney')
Austin Reaves
18.5
184.92499999999998
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Klay Thompson')
LeBron James
17.249999999999993
169.75833333333333
('Anthony Davis', 'Jordan Poole', 'Stephen Curry', 'Jonathan Kuminga', 'Austin Reaves')
171.22499999999997
('Anthony Davis', 'Jordan Poole', 'Jonathan Kuminga', 'Klay Thompson', 'Kevon Looney')

In [205]:
temp_chosen

[{'Andrew Wiggins': 30.075000000000003},
 {192.075: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Kevon Looney')},
 {'Donte DiVincenzo': 8.06249999999999},
 {174.48749999999998: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Draymond Green': 27.499999999999993},
 {193.92499999999998: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'JaMychal Green': 13.242857142857149},
 {179.66785714285714: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'James Wiseman': 26.362499999999994},
 {192.78749999999997: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Jerome Robinson': 11.276785714285715},
 {177.7017857142857: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Jonathan Kuminga': 49.08749999999999},
 {204.61249999999995: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Klay Thompson',
   'Kevon Looney')},
 {'Jordan Poole': 51.637499999999996},
 {205.46249999999998: ('Anthony Davis',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson',
   'Kevon Looney')},
 {'Kevon Looney': 32.737500000000004},
 {199.1625: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Klay Thompson': 39.375},
 {201.375: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Kevon Looney')},
 {'Lester Quinones': 1.8750000000000053},
 {168.29999999999998: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Pat Spencer': 3.0750000000000064},
 {169.5: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Quinndary Weatherspoon': 7.167857142857143},
 {173.59285714285713: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Ryan Rollins': 4.875},
 {171.29999999999998: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'Stephen Curry': 51.412499999999994},
 {205.38749999999996: ('Anthony Davis',
   'Jordan Poole',
   'Jonathan Kuminga',
   'Klay Thompson',
   'Kevon Looney')},
 {'Anthony Davis': 58.125},
 {207.625: ('Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson',
   'Kevon Looney')},
 {'Austin Reaves': 18.5},
 {184.92499999999998: ('Anthony Davis',
   'Jordan Poole',
   'Stephen Curry',
   'Jonathan Kuminga',
   'Klay Thompson')},
 {'LeBron James': 17.249999999999993},
 {171.22499999999997: ('Anthony Davis',
   'Jordan Poole',
   'Jonathan Kuminga',
   'Klay Thompson',
   'Kevon Looney')}]

In [107]:

total_lists = []
alt_chosen = []

for i in name_list:
    row = nba_stats.loc[nba_stats["Name"] == i]
    score = row["Alt_Salary"].tolist()[0] * 1.5
    max_salary = 50000 - row["CPT_Salary"].tolist()[0]

    comb = nba_stats.drop(index = index_drop)
    comb = comb.sort_values("Alt_Salary", ascending=False).copy()
    cpt_name = row["Name"].tolist()[0]
    print(cpt_name)
    alt_chosen.append({cpt_name : score})

    legit = ()
    max_score = 0

    comb = comb.drop(row.index)
    for combo in combinations(comb["Name"], 5):  # 2 for pairs, 3 for triplets, etc
        total_score = 0
        total_salary = 0
        for x in combo:
            rowP = nba_stats.loc[nba_stats["Name"] == x]
            total_score = total_score + rowP["Alt_Salary"].tolist()[0]
            total_salary = total_salary + rowP["UTIL_salary"].tolist()[0]
        total_score = total_score + score
        if total_salary < max_salary:
            if total_score > max_score:
                team_salary = total_salary
                print(total_score)
                max_score = total_score
                legit = combo
                print(legit)
                
    alt_chosen.append({max_score : legit})

Jayson Tatum
213.89499999999998
('Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Derrick White', 'Gary Payton II')
221.03500000000003
('Klay Thompson', 'Jordan Poole', 'Al Horford', 'Draymond Green', 'Derrick White')
Stephen Curry
211.64499999999998
('Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Derrick White', 'Gary Payton II')
215.72500000000002
('Jordan Poole', 'Al Horford', 'Draymond Green', 'Robert Williams', 'Derrick White')
Jaylen Brown
212.065
('Jayson Tatum', 'Klay Thompson', 'Jordan Poole', 'Derrick White', 'Gary Payton II')
213.825
('Jayson Tatum', 'Jordan Poole', 'Al Horford', 'Draymond Green', 'Gary Payton II')
Al Horford
215.74
('Jayson Tatum', 'Stephen Curry', 'Jordan Poole', 'Draymond Green', 'Gary Payton II')
219.45
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Draymond Green', 'Derrick White')
Andrew Wiggins
209.61
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Gary Payton II')
212.82000000000002
('Jayson Tatum', 'Klay Thompson', 'Jordan Poole', 'Al Horford', 'Derrick White')
213.69
('Jayson Tatum', 'Jordan Poole', 'Al Horford', 'Draymond Green', 'Robert Williams')
Klay Thompson
212.59500000000003
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Gary Payton II')
213.815
('Jayson Tatum', 'Jordan Poole', 'Andrew Wiggins', 'Al Horford', 'Derrick White')
216.675
('Jayson Tatum', 'Jordan Poole', 'Al Horford', 'Draymond Green', 'Robert Williams')
Marcus Smart
209.055
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Gary Payton II')
212.26500000000001
('Jayson Tatum', 'Klay Thompson', 'Jordan Poole', 'Al Horford', 'Derrick White')
213.135
('Jayson Tatum', 'Jordan Poole', 'Al Horford', 'Draymond Green', 'Robert Williams')
Draymond Green
215.69
('Jayson Tatum', 'Stephen Curry', 'Jordan Poole', 'Al Horford', 'Gary Payton II')
219.40000000000003
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Derrick White')
Jordan Poole
218.155
('Jayson Tatum', 'Stephen Curry', 'Klay Thompson', 'Al Horford', 'Gary Payton II')
221.865
('Jayson Tatum', 'Jaylen Brown', 'Klay Thompson', 'Al Horford', 'Derrick White')
Kevon Looney
203.025
('Jayson Tatum', 'Stephen Curry', 'Klay Thompson', 'Jordan Poole', 'Gary Payton II')
206.735
('Jayson Tatum', 'Jaylen Brown', 'Klay Thompson', 'Jordan Poole', 'Derrick White')
208.495
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Draymond Green')
Derrick White
211.965
('Jayson Tatum', 'Stephen Curry', 'Klay Thompson', 'Jordan Poole', 'Gary Payton II')
217.435
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Draymond Green')
Gary Payton II
210.89000000000001
('Jayson Tatum', 'Stephen Curry', 'Klay Thompson', 'Jordan Poole', 'Al Horford')
Robert Williams
214.50500000000002
('Jayson Tatum', 'Stephen Curry', 'Jordan Poole', 'Al Horford', 'Gary Payton II')
218.21500000000003
('Jayson Tatum', 'Jaylen Brown', 'Jordan Poole', 'Al Horford', 'Derrick White')

In [108]:
alt_chosen

[{'Jayson Tatum': 71.205},
 {221.03500000000003: ('Klay Thompson',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Derrick White')},
 {'Stephen Curry': 68.955},
 {215.72500000000002: ('Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Robert Williams',
   'Derrick White')},
 {'Jaylen Brown': 59.205},
 {213.825: ('Jayson Tatum',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Gary Payton II')},
 {'Al Horford': 45.45},
 {219.45: ('Jayson Tatum',
   'Jaylen Brown',
   'Jordan Poole',
   'Draymond Green',
   'Derrick White')},
 {'Andrew Wiggins': 45.72},
 {213.69: ('Jayson Tatum',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Robert Williams')},
 {'Klay Thompson': 48.705},
 {216.675: ('Jayson Tatum',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Robert Williams')},
 {'Marcus Smart': 45.165},
 {213.135: ('Jayson Tatum',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green',
   'Robert Williams')},
 {'Draymond Green': 45.3},
 {219.40000000000003: ('Jayson Tatum',
   'Jaylen Brown',
   'Jordan Poole',
   'Al Horford',
   'Derrick White')},
 {'Jordan Poole': 45.885},
 {221.865: ('Jayson Tatum',
   'Jaylen Brown',
   'Klay Thompson',
   'Al Horford',
   'Derrick White')},
 {'Kevon Looney': 30.464999999999996},
 {208.495: ('Jayson Tatum',
   'Jaylen Brown',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green')},
 {'Derrick White': 39.405},
 {217.435: ('Jayson Tatum',
   'Jaylen Brown',
   'Jordan Poole',
   'Al Horford',
   'Draymond Green')},
 {'Gary Payton II': 24.089999999999996},
 {210.89000000000001: ('Jayson Tatum',
   'Stephen Curry',
   'Klay Thompson',
   'Jordan Poole',
   'Al Horford')},
 {'Robert Williams': 44.115},
 {218.21500000000003: ('Jayson Tatum',
   'Jaylen Brown',
   'Jordan Poole',
   'Al Horford',
   'Derrick White')}]