In [1]:
import pandas as pd

In [34]:
date = input("Date")
team = input("Team")

Date2022-06-10 00:00:00
TeamBoston

In [35]:
pred = pd.read_csv(f"Final_Score/LSTM/Backtesting/{team}/{team}_{date}.csv", index_col=0)
pred

                             0
Aaron Nesmith         4.883414
Al Horford           29.192957
Daniel Theis         22.676270
Derrick White         9.558358
Grant Williams       24.208330
Jaylen Brown         38.859707
Jayson Tatum         40.154156
Juwan Morgan          0.337428
Luke Kornet          -0.025873
Malik Fitts          -2.610331
Marcus Smart         31.236488
Nik Stauskas          0.377910
Payton Pritchard     11.246497
Robert Williams III  24.448553
Sam Hauser           -0.004159

In [30]:
date = "2022-06-10"

In [31]:
test = pd.read_csv("Final_Score/Tables/Boston_Celtics.csv", index_col=0)
test

,Aaron Nesmith,Al Horford,Daniel Theis,Derrick White,Grant Williams,Jaylen Brown,Jayson Tatum,Juwan Morgan,Luke Kornet,Malik Fitts,Marcus Smart,Nik Stauskas,Payton Pritchard,Robert Williams III,Sam Hauser,0,Datetime
06/16/2022,0.00,46.00,NaN,5.75,7.25,49.25,33.25,0.00,0.75,NaN,33.00,0.00,2.25,30.75,0.00,Golden State Warriors,2022-06-16
06/02/2022,0.00,42.00,5.50,28.25,8.25,45.25,39.25,0.00,NaN,0.00,36.25,0.00,19.50,24.50,0.00,Golden State Warriors,2022-06-02
06/10/2022,NaN,24.00,NaN,20.75,4.75,33.50,52.75,NaN,NaN,NaN,39.00,NaN,1.75,34.00,NaN,Golden State Warriors,2022-06-10
06/05/2022,11.50,14.50,9.25,25.50,11.25,29.50,43.00,NaN,3.50,3.50,11.50,8.75,13.50,10.00,5.00,Golden State Warriors,2022-06-05
06/13/2022,4.25,21.75,NaN,8.75,11.25,34.75,46.00,1.25,4.75,NaN,26.25,0.00,0.75,23.00,1.50,Golden State Warriors,2022-06-13
04/17/2022,NaN,44.25,13.00,22.25,13.00,45.25,53.00,NaN,NaN,NaN,42.25,NaN,4.75,NaN,NaN,Brooklyn Nets,2022-04-17
05/25/2022,0.00,38.25,NaN,27.25,12.50,36.00,49.00,0.00,0.00,0.00,17.25,0.00,1.25,26.50,NaN,Miami Heat,2022-05-25
05/19/2022,1.25,21.75,4.75,NaN,27.00,40.00,43.25,2.25,4.50,NaN,63.25,7.75,18.50,17.50,NaN,Miami Heat,2022-05-19
05/27/2022,0.00,20.75,NaN,43.25,6.50,37.50,51.75,NaN,NaN,NaN,25.00,NaN,0.00,18.75,NaN,Miami Heat,2022-05-27
05/23/2022,10.25,34.25,7.75,39.00,16.25,23.75,51.50,0.00,NaN,0.00,NaN,2.00,26.00,27.25,NaN,Miami Heat,2022-05-23
05/21/2022,0.00,48.00,5.25,8.00,20.75,54.75,21.00,1.25,0.00,0.00,30.00,3.50,9.50,NaN,NaN,Miami Heat,2022-05-21
05/09/2022,NaN,48.50,2.25,23.00,13.50,25.25,54.25,NaN,NaN,NaN,36.00,NaN,11.75,NaN,NaN,Milwaukee Bucks,2022-05-09
05/11/2022,NaN,34.50,14.75,28.25,3.00,47.50,52.00,NaN,NaN,NaN,27.50,NaN,8.00,NaN,NaN,Milwaukee Bucks,2022-05-11
05/07/2022,NaN,55.50,0.75,19.50,25.50,48.50,24.25,NaN,NaN,NaN,15.50,NaN,7.00,32.25,NaN,Milwaukee Bucks,2022-05-07
05/13/2022,1.25,28.50,6.50,22.75,13.25,37.25,66.75,NaN,NaN,NaN,40.25,2.00,3.50,NaN,NaN,Milwaukee Bucks,2022-05-13
05/17/2022,8.75,NaN,18.00,10.00,12.75,44.00,55.50,NaN,NaN,NaN,NaN,NaN,33.75,34.25,NaN,Miami Heat,2022-05-17
05/03/2022,1.25,39.25,NaN,13.50,33.25,54.50,53.25,NaN,1.25,1.25,NaN,0.00,14.75,20.00,3.25,Milwaukee Bucks,2022-05-03
05/29/2022,NaN,33.50,NaN,14.75,19.50,39.00,54.50,NaN,NaN,NaN,47.75,NaN,0.00,6.75,NaN,Miami Heat,2022-05-29
05/15/2022,4.75,29.50,9.75,9.50,41.50,33.00,43.50,0.00,0.00,3.50,38.25,1.50,26.75,NaN,NaN,Milwaukee Bucks,2022-05-15
05/01/2022,2.75,36.00,6.00,16.50,16.00,31.25,42.00,NaN,0.00,3.25,23.25,0.00,9.50,24.00,0.00,Milwaukee Bucks,2022-05-01
06/08/2022,1.25,34.50,NaN,14.75,18.25,48.75,49.50,0.00,NaN,0.00,39.25,0.00,4.50,34.50,0.00,Golden State Warriors,2022-06-08
04/25/2022,NaN,23.00,20.50,19.50,26.75,38.00,39.25,NaN,NaN,NaN,43.75,NaN,4.25,10.75,NaN,Brooklyn Nets,2022-04-25
04/20/2022,NaN,34.00,26.50,8.25,30.00,41.00,43.00,NaN,NaN,NaN,21.25,NaN,16.00,NaN,NaN,Brooklyn Nets,2022-04-20
04/23/2022,NaN,15.25,20.00,12.50,16.75,38.50,65.25,NaN,NaN,NaN,30.75,NaN,14.50,8.00,NaN,Brooklyn Nets,2022-04-23

In [32]:
test.loc[test["Datetime"] == date]

,Aaron Nesmith,Al Horford,Daniel Theis,Derrick White,Grant Williams,Jaylen Brown,Jayson Tatum,Juwan Morgan,Luke Kornet,Malik Fitts,Marcus Smart,Nik Stauskas,Payton Pritchard,Robert Williams III,Sam Hauser,0,Datetime
06/10/2022,NaN,24.0,NaN,20.75,4.75,33.5,52.75,NaN,NaN,NaN,39.0,NaN,1.75,34.0,NaN,Golden State Warriors,2022-06-10

In [36]:
pred

                             0
Aaron Nesmith         4.883414
Al Horford           29.192957
Daniel Theis         22.676270
Derrick White         9.558358
Grant Williams       24.208330
Jaylen Brown         38.859707
Jayson Tatum         40.154156
Juwan Morgan          0.337428
Luke Kornet          -0.025873
Malik Fitts          -2.610331
Marcus Smart         31.236488
Nik Stauskas          0.377910
Payton Pritchard     11.246497
Robert Williams III  24.448553
Sam Hauser           -0.004159