In [9]:
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
import os
from sklearn.metrics import r2_score

In [2]:
# create dictionary 
final_data = {}

In [166]:
team = 'Dallas Mavericks'

In [167]:
#obtain list of dates
directory = team
list_dates = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        list_dates.append(filename)

In [168]:
# reads in each csv
for i in list_dates:
    data = pd.read_csv(f"{team}/{i}", index_col=0)
    
    #gathers data and adds to dict
    date = data["Date"].tolist()[0]
    data[date] = data["Score"]
    final_data[date] = data[date]

In [169]:
#obtain list of dates
directory = f'{team}'
list_dates = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"):
        list_dates.append(filename)

# reads in each csv
for i in list_dates:
    data = pd.read_csv(f"{directory}/{i}", index_col=0)

    #gathers data and adds to dict
    date = data["Date"].tolist()[0]
    data[date] = data["Score"]
    final_data[date] = data[date]

# convert dict to dataframe
data_df = pd.DataFrame(final_data)

t = data_df.transpose()

t['Datetime'] = pd.to_datetime(t.index)

data = t.sort_values(by='Datetime')

data_df = t.sort_values(by='Datetime').transpose()

In [170]:
#create dict
final_result = {}

In [174]:
#iterate through index
for name in data_df.index[:-1]:
    #create linear regression model 
    model = LinearRegression()
    
    final_result[name] = {}
    
    # get dataframe with each name 
    finder = data_df[data_df.index == name]
    
    #obtain length of dataset
    X = []
    for x in range(len(finder.columns)):
        X.append(x)
        
    stats = data[[name]].dropna().head(3).transpose()
            
    #obtain length of dataset
    X = []
    for x in range(len(stats.columns)):
        X.append(x)

    # create dataframe for each player
    XX = pd.DataFrame(X)
    XX["Score"] = stats[0]
    XX.dropna(inplace=True)
    length = len(XX[0])
    
    #reshape values
    X_values = XX[0].values.reshape(-1, 1)
    
    #fit linear regression model
    model.fit(X_values, XX["Score"])
    #predict next game
    predict = [length]
    
    #create dataframe of final prediction and add to dict
    prediction = pd.DataFrame(predict)
    prediction[0].values.reshape(-1,1)
    final_prediction = model.predict(prediction[0].values.reshape(-1,1))
    final_result[name]['Predict'] = final_prediction[0]
        
    final_result[name]['R^2'] = r2_score(XX["Score"], model.predict(X_values))

KeyError: 0

In [89]:
# convert dict to dataframe
Data = pd.DataFrame.from_dict(final_result, orient='index')

In [96]:
pd.DataFrame(Data['R^2'].tolist()).dropna()[0].mean()

0.4775910171051587

In [75]:
Data

                       Predict       R^2
Christian Wood        5.675000  0.851701
Dorian Finney-Smith  29.075000  0.448676
Dwight Powell        11.884615  0.765300
Facundo Campazzo      3.500000  1.000000
JaVale McGee          3.457143  0.995722
Jaden Hardy           1.916667  1.000000
Josh Green           19.625000  0.266152
Luka Doncic          63.525000  0.057761
Maxi Kleber           7.150000  0.868308
McKinley Wright IV    9.500000       NaN
Reggie Bullock       10.875000  0.223887
Spencer Dinwiddie    31.000000  0.111088
Theo Pinson           6.000000       NaN
Tim Hardaway Jr.     24.550000  0.021755
Tyler Dorsey         12.000000       NaN

In [56]:
Data

                          Predict       R^2
Christian Wood       2.003548e+01  0.149913
Dorian Finney-Smith  1.775000e+01  0.000308
Dwight Powell        1.276996e+01  0.025030
Facundo Campazzo     3.500000e+00  1.000000
JaVale McGee         3.789278e+00  0.424951
Jaden Hardy          1.916667e+00  1.000000
Josh Green           1.706667e+01  0.096470
Luka Doncic          6.111667e+01  0.040278
Maxi Kleber          7.400000e+00  0.451395
McKinley Wright IV   9.500000e+00       NaN
Reggie Bullock       5.300000e+00  0.418758
Spencer Dinwiddie    4.166667e+01  0.236317
Theo Pinson          6.000000e+00       NaN
Tim Hardaway Jr.     1.787460e+01  0.018856
Tyler Dorsey         1.200000e+01       NaN
Datetime             1.668344e+18       NaN

In [26]:
# convert dataframe to csv
mypath = "Final_Score"
if not os.path.isdir(mypath):
    os.makedirs(mypath)
Data.to_csv(f"{mypath}/{team}.csv", index=True)

In [160]:
teams = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "LA Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards"
]

In [172]:
# test

nums = [3, 5, 7, 10]

results = {}

for num in nums:

    #create dict
    final_result = {}

    for team in teams:

        #obtain list of dates
        directory = f'Historical/{team}'
        list_dates = []
        for filename in os.listdir(directory):
            if filename.endswith(".csv"):
                list_dates.append(filename)

        # reads in each csv
        for i in list_dates:
            data = pd.read_csv(f"{directory}/{i}", index_col=0)

            #gathers data and adds to dict
            date = data["Date"].tolist()[0]
            data[date] = data["Score"]
            final_data[date] = data[date]

        # convert dict to dataframe
        data_df = pd.DataFrame(final_data)

        t = data_df.transpose()

        t['Datetime'] = pd.to_datetime(t.index)
        
        data = t.sort_values(by='Datetime')

        data_df = t.sort_values(by='Datetime').transpose()

        #iterate through index
        for name in data_df.index[:-1]:
            #create linear regression model 
            model = LinearRegression()

            final_result[name] = {}

            # get dataframe with each name 
            finder = data_df[data_df.index == name]

            #obtain length of dataset
            X = []
            for x in range(len(finder.columns)):
                X.append(x)

            stats = data[[name]].dropna().head(num).transpose()
            
            #obtain length of dataset
            X = []
            for x in range(len(stats.columns)):
                X.append(x)

            stats = stats[stats.index == name].values

            # create dataframe for each player
            XX = pd.DataFrame(X)
            XX["Score"] = stats[0]
            XX.dropna(inplace=True)
            length = len(XX[0])
            
            if length < num:
                continue

            #reshape values
            X_values = XX[0].values.reshape(-1, 1)

            #fit linear regression model
            model.fit(X_values, XX["Score"])
            #predict next game
            predict = [length]

            #create dataframe of final prediction and add to dict
            prediction = pd.DataFrame(predict)
            prediction[0].values.reshape(-1,1)
            final_prediction = model.predict(prediction[0].values.reshape(-1,1))
            final_result[name]['Predict'] = final_prediction[0]

            final_result[name]['R^2'] = r2_score(XX["Score"], model.predict(X_values))
            
    # convert dict to dataframe
    Data = pd.DataFrame.from_dict(final_result, orient='index')
    
    m = pd.DataFrame(Data['R^2'].tolist()).dropna()[0].mean()
    
    results[num] = m

In [173]:
results

{3: 0.5640562185013309,
 5: 0.25365764890759634,
 7: 0.20009731128684025,
 10: 0.11308335580860225}

In [164]:
XX

   0  Score
0  0  26.50
1  1  28.75